builds:
- id: "oomkill-watch"
  binary: oomkill-watch
  goos:
  - linux
  - darwin
  goarch:
  - amd64
checksum:
  name_template: 'checksums.txt'
dist: /tmp/oomkill-watch/dist
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
release:
  github:
    owner: flowerinthenight
    name: oomkill-watch
brews:
- repository:
    owner: flowerinthenight
    name: homebrew-tap
  name: oomkill-watch
  homepage: "https://github.com/flowerinthenight/oomkill-watch"
  description: "A simple kubectl wrapper tool for tailing OOMKilling events."
  directory: Formula
  install: |
    bin.install "oomkill-watch"
  test: |
    assert_match /Usage of/, shell_output("#{bin}/oomkill-watch -h", 0)
